theme: jekyll-theme-leap-day
markdown: kramdown
title: Taller de Programación
description: Universidad de Sevilla. Octubre 2018
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "pages"